-- Optional: run this after schema.sql to populate ~40 "neighbor" profiles so the
-- map and search aren't empty before real people sign up. These addresses are
-- generated deterministically by src/world/generateWorld.ts, so they match the
-- houses the app actually renders. Regenerate by re-running the script that
-- produced this file (see git history) whenever the world generator changes shape.
insert into profiles (username, address_id, is_npc) values
  ('Alex', 'b-0-0-n0-h3', true),
  ('Mika', 'b-0-5-n0-h2', true),
  ('Noa', 'b-1-1-n0-h4', true),
  ('Jordan', 'b-1-2-n1-h2', true),
  ('Sam', 'b-2-2-n0-h2', true),
  ('Ravi', 'b-2-2-n2-h3', true),
  ('Yuki', 'b-2-3-n2-h1', true),
  ('Leo', 'b-3-2-n0-h0', true),
  ('Ines', 'b-3-2-n2-h2', true),
  ('Theo', 'b-3-3-n0-h3', true),
  ('Dana', 'b-3-5-n0-h2', true),
  ('Omar', 'b-3-6-n0-h3', true),
  ('Priya', 'b-3-8-n0-h1', true),
  ('Kai', 'b-4-0-n1-h0', true),
  ('Liam', 'b-4-3-n1-h1', true),
  ('Zoe', 'b-4-5-n2-h0', true),
  ('Finn', 'b-4-6-n1-h1', true),
  ('Maya', 'b-4-7-n0-h1', true),
  ('Eli', 'b-5-2-n0-h0', true),
  ('Ana', 'b-5-2-n1-h3', true),
  ('Nina', 'b-5-3-n1-h0', true),
  ('Toby', 'b-5-4-n0-h2', true),
  ('Rami', 'b-5-5-n0-h3', true),
  ('Sara', 'b-5-5-n2-h2', true),
  ('Ivo', 'b-5-6-n0-h1', true),
  ('Lior', 'b-5-7-n1-h1', true),
  ('Amara', 'b-6-1-n1-h0', true),
  ('Jules', 'b-6-3-n1-h1', true),
  ('Pia', 'b-6-4-n0-h2', true),
  ('Otis', 'b-6-5-n0-h3', true),
  ('Talia', 'b-6-5-n2-h2', true),
  ('Marco', 'b-6-6-n1-h1', true),
  ('Yara', 'b-6-7-n0-h0', true),
  ('Ben', 'b-7-2-n0-h1', true),
  ('Coco', 'b-7-3-n0-h4', true),
  ('Dev', 'b-7-4-n2-h0', true),
  ('Elin', 'b-7-5-n0-h3', true),
  ('Farid', 'b-7-6-n1-h1', true),
  ('Gaia', 'b-7-8-n0-h3', true),
  ('Huck', 'b-8-5-n1-h2', true);
