-- Optional: run this after schema.sql to populate ~40 "neighbor" profiles so the
-- map and search aren't empty before real people sign up. These addresses are
-- generated deterministically by src/world/generateWorld.ts, so they match the
-- houses the app actually renders. Regenerate with:
--   npx tsx -e "<see git history for the generator script>" > supabase/seed.sql
insert into profiles (username, address_id, is_npc) values
  ('Alex', 'b-0-2-h5', true),
  ('Mika', 'b-0-5-h2', true),
  ('Noa', 'b-0-7-h11', true),
  ('Jordan', 'b-0-11-h8', true),
  ('Sam', 'b-1-2-h5', true),
  ('Ravi', 'b-1-8-h2', true),
  ('Yuki', 'b-2-1-h11', true),
  ('Leo', 'b-2-7-h8', true),
  ('Ines', 'b-2-11-h5', true),
  ('Theo', 'b-3-8-h2', true),
  ('Dana', 'b-3-10-h11', true),
  ('Omar', 'b-4-4-h8', true),
  ('Priya', 'b-4-7-h5', true),
  ('Kai', 'b-4-11-h2', true),
  ('Liam', 'b-5-1-h11', true),
  ('Zoe', 'b-5-4-h8', true),
  ('Finn', 'b-5-8-h5', true),
  ('Maya', 'b-5-11-h2', true),
  ('Eli', 'b-6-1-h11', true),
  ('Ana', 'b-6-7-h8', true),
  ('Nina', 'b-6-10-h5', true),
  ('Toby', 'b-7-0-h2', true),
  ('Rami', 'b-7-2-h11', true),
  ('Sara', 'b-7-8-h8', true),
  ('Ivo', 'b-7-12-h5', true),
  ('Lior', 'b-8-3-h2', true),
  ('Amara', 'b-8-7-h11', true),
  ('Jules', 'b-8-10-h8', true),
  ('Pia', 'b-9-0-h5', true),
  ('Otis', 'b-9-4-h2', true),
  ('Talia', 'b-9-8-h11', true),
  ('Marco', 'b-10-1-h8', true),
  ('Yara', 'b-10-7-h5', true),
  ('Ben', 'b-10-12-h2', true),
  ('Coco', 'b-11-1-h11', true),
  ('Dev', 'b-11-5-h8', true),
  ('Elin', 'b-11-11-h5', true),
  ('Farid', 'b-12-1-h2', true),
  ('Gaia', 'b-12-4-h11', true),
  ('Huck', 'b-12-11-h8', true);
